default_platform(:android)

platform :android do
  desc "Upload to firebase"
   lane :test do
    sh('flutter build apk')
    release = firebase_app_distribution(
                    app: "1:378784049028:android:25def2d5a15e225be5dfd1",
                    groups: "beta",
                    release_notes: "App for fastlane",
                    apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
                    firebase_cli_path: "/usr/local/bin/firebase",
                    firebase_cli_token: "1//0gQXmeVbnloQBCgYIARAAGBASNwF-L9Irb5djU6GzM4BUBssnhz_HBXK3C3GYNBooRqwgG75Tm3i4gW48w2DMKKsLoRQ1kK-ga38",
                )
   end
end
