name: Flutter CI/CD

on:
  push:
    branches:
    - main

jobs:
  build:
    name : Build & Release
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.0'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.1'

      - name: Run Script
        run: |
          sh ./build_and_release.sh




