name: Flutter CI/CD

on:
  push:
    branches:
    - main

jobs:
  build:
    name : Build & Release
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.0'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.1'

      - name: Run Script
        run: |
          sh ./build_and_release.sh

      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/*
          tag: v1.1.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          name: Firebase Deploy

      # build here
      - name: Upload headquarter artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: build/app/outputs/flutter-apk/headquarter.apk




